astra_db:
  key_space : "default_keyspace" 
  collection_name : "doc_analysis_chat"


embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

llm:
  groq:
    provider: "groq"
    model_name: "openai/gpt-oss-20b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048 

retriever:
  top_k: 20
  max_history_messages: 4

doc_ingestion:
  supported_extensions : {".pdf", ".docx", ".txt" , ".md"}
